# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from can_package/CONTROL_MSG.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CONTROL_MSG(genpy.Message):
  _md5sum = "4e1b84ccf5a5c6a0e362e2cdfaeae72d"
  _type = "can_package/CONTROL_MSG"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 EPS_en  
uint8 ControlSW
uint8 EPS_Interval  
uint8 SCC_En    
uint8 AEB_Act
uint8 AEB_decel_value
uint8 Alive_count
float32 SCC_value
float32 EPS_value
"""
  __slots__ = ['EPS_en','ControlSW','EPS_Interval','SCC_En','AEB_Act','AEB_decel_value','Alive_count','SCC_value','EPS_value']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8','uint8','uint8','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       EPS_en,ControlSW,EPS_Interval,SCC_En,AEB_Act,AEB_decel_value,Alive_count,SCC_value,EPS_value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CONTROL_MSG, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.EPS_en is None:
        self.EPS_en = 0
      if self.ControlSW is None:
        self.ControlSW = 0
      if self.EPS_Interval is None:
        self.EPS_Interval = 0
      if self.SCC_En is None:
        self.SCC_En = 0
      if self.AEB_Act is None:
        self.AEB_Act = 0
      if self.AEB_decel_value is None:
        self.AEB_decel_value = 0
      if self.Alive_count is None:
        self.Alive_count = 0
      if self.SCC_value is None:
        self.SCC_value = 0.
      if self.EPS_value is None:
        self.EPS_value = 0.
    else:
      self.EPS_en = 0
      self.ControlSW = 0
      self.EPS_Interval = 0
      self.SCC_En = 0
      self.AEB_Act = 0
      self.AEB_decel_value = 0
      self.Alive_count = 0
      self.SCC_value = 0.
      self.EPS_value = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7B2f().pack(_x.EPS_en, _x.ControlSW, _x.EPS_Interval, _x.SCC_En, _x.AEB_Act, _x.AEB_decel_value, _x.Alive_count, _x.SCC_value, _x.EPS_value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 15
      (_x.EPS_en, _x.ControlSW, _x.EPS_Interval, _x.SCC_En, _x.AEB_Act, _x.AEB_decel_value, _x.Alive_count, _x.SCC_value, _x.EPS_value,) = _get_struct_7B2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7B2f().pack(_x.EPS_en, _x.ControlSW, _x.EPS_Interval, _x.SCC_En, _x.AEB_Act, _x.AEB_decel_value, _x.Alive_count, _x.SCC_value, _x.EPS_value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 15
      (_x.EPS_en, _x.ControlSW, _x.EPS_Interval, _x.SCC_En, _x.AEB_Act, _x.AEB_decel_value, _x.Alive_count, _x.SCC_value, _x.EPS_value,) = _get_struct_7B2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7B2f = None
def _get_struct_7B2f():
    global _struct_7B2f
    if _struct_7B2f is None:
        _struct_7B2f = struct.Struct("<7B2f")
    return _struct_7B2f
