# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from can_package/FB_EAIT_SPD.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FB_EAIT_SPD(genpy.Message):
  _md5sum = "942f3c288489605fdeb5cae068a7cd8a"
  _type = "can_package/FB_EAIT_SPD"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
uint16 WHL_SPD_FL    # 0|14@1+ (0.03125,0) [0|511.96875]
uint16 WHL_SPD_FR    # 16|14@1+ (0.03125,0) [0|511.96875]
uint16 WHL_SPD_RL    # 32|14@1+ (0.03125,0) [0|511.96875]
uint16 WHL_SPD_RR    # 48|14@1+ (0.03125,0) [0|511.96875]
"""
  __slots__ = ['WHL_SPD_FL','WHL_SPD_FR','WHL_SPD_RL','WHL_SPD_RR']
  _slot_types = ['uint16','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       WHL_SPD_FL,WHL_SPD_FR,WHL_SPD_RL,WHL_SPD_RR

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FB_EAIT_SPD, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.WHL_SPD_FL is None:
        self.WHL_SPD_FL = 0
      if self.WHL_SPD_FR is None:
        self.WHL_SPD_FR = 0
      if self.WHL_SPD_RL is None:
        self.WHL_SPD_RL = 0
      if self.WHL_SPD_RR is None:
        self.WHL_SPD_RR = 0
    else:
      self.WHL_SPD_FL = 0
      self.WHL_SPD_FR = 0
      self.WHL_SPD_RL = 0
      self.WHL_SPD_RR = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4H().pack(_x.WHL_SPD_FL, _x.WHL_SPD_FR, _x.WHL_SPD_RL, _x.WHL_SPD_RR))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.WHL_SPD_FL, _x.WHL_SPD_FR, _x.WHL_SPD_RL, _x.WHL_SPD_RR,) = _get_struct_4H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4H().pack(_x.WHL_SPD_FL, _x.WHL_SPD_FR, _x.WHL_SPD_RL, _x.WHL_SPD_RR))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.WHL_SPD_FL, _x.WHL_SPD_FR, _x.WHL_SPD_RL, _x.WHL_SPD_RR,) = _get_struct_4H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4H = None
def _get_struct_4H():
    global _struct_4H
    if _struct_4H is None:
        _struct_4H = struct.Struct("<4H")
    return _struct_4H
